development:
  auth0_domain: dev-0o8ma8wwhjzzxtts.us.auth0.com
  auth0_client_id: Uu94qDN2meRUxQ5mwShCOG5JqlfZLP2r
  auth0_client_secret: QLSaUXh1PEItnpUT5bXqF21Nbn0RkKrClmduqK7ixT7eVf2W-tC79nxMXmtO0nqL