default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: supersecret
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: cleanbooking_test

production:
  <<: *default
  database: cleanbooking_production
  username: cleanbooking
  password: <%= ENV['CLEANBOOKING_DATABASE_PASSWORD'] %>
